/*
 * Mainnet Cash
 *
 * A developer friendly bitcoin cash wallet api  This API is currently in *active* development, breaking changes may be made prior to official release of version 1.0.0. 
 *
 * API version: 1.0.14
 * Contact: hello@mainnet.cash
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// DepositAddressResponse struct for DepositAddressResponse
type DepositAddressResponse struct {
	Cashaddr string `json:"cashaddr,omitempty"`
}
