/*
 * Mainnet Cash
 *
 * A developer friendly bitcoin cash wallet api  This API is currently in *active* development, breaking changes may be made prior to official release of version 1.0.0. 
 *
 * API version: 4.0.0-next.14
 * Contact: hello@mainnet.cash
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TokenMintItem struct for TokenMintItem
type TokenMintItem struct {
	// Token unique hexadecimal identifier, also the id of the token creation transaction. The minting NFT spent for this mint must be of this category.
	Category string `json:"category"`
	Nft *TokenNft `json:"nft,omitempty"`
	// Cashaddress to send tokens to
	Cashaddr string `json:"cashaddr,omitempty"`
	// Satoshi value to send alongside with tokens
	Value float32 `json:"value,omitempty"`
}
