/*
 * Mainnet Cash
 *
 * A developer friendly bitcoin cash wallet api  This API is currently in *active* development, breaking changes may be made prior to official release of version 1.0.0. 
 *
 * API version: 2.7.31
 * Contact: hello@mainnet.cash
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// GetTestnetBchRequest struct for GetTestnetBchRequest
type GetTestnetBchRequest struct {
	// Receiver's cashaddr
	Cashaddr string `json:"cashaddr,omitempty"`
}
