/*
 * Mainnet Cash
 *
 * A developer friendly bitcoin cash wallet api  This API is currently in *active* development, breaking changes may be made prior to official release of version 1.0.0. 
 *
 * API version: 4.0.0-next.11
 * Contact: hello@mainnet.cash
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TokenGenesisItem struct for TokenGenesisItem
type TokenGenesisItem struct {
	// amount of *fungible* tokens to create
	Amount float32 `json:"amount,omitempty"`
	Nft *TokenNft `json:"nft,omitempty"`
	// Cashaddress to send tokens to
	Cashaddr string `json:"cashaddr,omitempty"`
	// Satoshi value to send alongside with tokens
	Value float32 `json:"value,omitempty"`
}
