/*
 * Mainnet Cash
 *
 * A developer friendly bitcoin cash wallet api  This API is currently in *active* development, breaking changes may be made prior to official release of version 1.0.0. 
 *
 * API version: 3.1.7
 * Contact: hello@mainnet.cash
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TokenNft struct for TokenNft
type TokenNft struct {
	// Capability of the NFT
	Capability string `json:"capability"`
	// Token commitment message, hexadecimal encoded, 40 bytes max length
	Commitment string `json:"commitment"`
}
