/*
 * Mainnet Cash
 *
 * A developer friendly bitcoin cash wallet api  This API is currently in *active* development, breaking changes may be made prior to official release of version 1.0.0. 
 *
 * API version: 3.0.0-next.3
 * Contact: hello@mainnet.cash
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// BalanceRequest struct for BalanceRequest
type BalanceRequest struct {
	// The walletId to get a balance for. 
	WalletId string `json:"walletId"`
	// This flag requires an utxo to have more than 546 sats to be spendable and counted in the balance This option is not switched on by default
	SlpSemiAware bool `json:"slpSemiAware,omitempty"`
}
