/*
 * Mainnet Cash
 *
 * A developer friendly bitcoin cash wallet api  This API is currently in *active* development, breaking changes may be made prior to official release of version 1.0.0. 
 *
 * API version: 4.0.0-next.12
 * Contact: hello@mainnet.cash
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TokenBurnItem struct for TokenBurnItem
type TokenBurnItem struct {
	// Token unique hexadecimal identifier, also the id of the token creation transaction
	Category string `json:"category"`
	Nft *TokenNft `json:"nft,omitempty"`
	// amount of fungible tokens to burn
	Amount float32 `json:"amount,omitempty"`
	// address to return token and satoshi change to, default to the sender's cashaddr
	Cashaddr string `json:"cashaddr,omitempty"`
}
