/*
 * Mainnet Cash
 *
 * A developer friendly bitcoin cash wallet api  This API is currently in *active* development, breaking changes may be made prior to official release of version 1.0.0. 
 *
 * API version: 3.0.0-next.8
 * Contact: hello@mainnet.cash
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// WalletReplaceNamedResponse True if operation was successful False if service database was not configured or other exception occured 
type WalletReplaceNamedResponse struct {
	Result bool `json:"result,omitempty"`
}
