/*
 * Mainnet Cash
 *
 * A developer friendly bitcoin cash wallet api  This API is currently in *active* development, breaking changes may be made prior to official release of version 1.0.0. 
 *
 * API version: 2.7.18
 * Contact: hello@mainnet.cash
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// SubmitTransactionResponse struct for SubmitTransactionResponse
type SubmitTransactionResponse struct {
	// The hash of a transaction
	TxId string `json:"txId,omitempty"`
}
