/*
 * Mainnet Cash
 *
 * A developer friendly bitcoin cash wallet api  This API is currently in *active* development, breaking changes may be made prior to official release of version 1.0.0. 
 *
 * API version: 3.0.0-next.9
 * Contact: hello@mainnet.cash
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// UtilDecodeTransactionRequest struct for UtilDecodeTransactionRequest
type UtilDecodeTransactionRequest struct {
	// network type
	Network string `json:"network,omitempty"`
}
