/*
 * Mainnet Cash
 *
 * A developer friendly bitcoin cash wallet api  This API is currently in *active* development, breaking changes may be made prior to official release of version 1.0.0. 
 *
 * API version: 2.6.7
 * Contact: hello@mainnet.cash
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// HistoryRequest struct for HistoryRequest
type HistoryRequest struct {
	// The walletId to get a history for. 
	WalletId string `json:"walletId"`
	// Unit of account for running balance.
	Unit string `json:"unit,omitempty"`
	// optional, if set, history will be limited. Default 0
	FromHeight float32 `json:"fromHeight,omitempty"`
	// optional, if set, history will be limited. Default -1, meaning that all history items will be returned, including mempool
	ToHeight float32 `json:"toHeight,omitempty"`
	// optional, if set, the result set will be paginated with offset `start`. Default 0
	Start float32 `json:"start,omitempty"`
	// optional, if set, the result set will be paginated with `count`. Default -1, meaning that all history items will be returned
	Count float32 `json:"count,omitempty"`
}
