/*
 * Mainnet Cash
 *
 * A developer friendly bitcoin cash wallet api  This API is currently in *active* development, breaking changes may be made prior to official release of version 1.0.0. 
 *
 * API version: 0.4.1
 * Contact: hello@mainnet.cash
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// WatchAddressResponse struct for WatchAddressResponse
type WatchAddressResponse struct {
	// Webhook Id created in the system
	Id int32 `json:"id,omitempty"`
}
