/*
 * Mainnet Cash
 *
 * A developer friendly bitcoin cash wallet api  This API is currently in *active* development, breaking changes may be made prior to official release of version 1.0.0. 
 *
 * API version: 1.0.13
 * Contact: hello@mainnet.cash
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// EncodeTransactionResponse struct for EncodeTransactionResponse
type EncodeTransactionResponse struct {
	// encoded transaction in hex format
	TransactionHex string `json:"transactionHex"`
}
