/*
 * Mainnet Cash
 *
 * A developer friendly bitcoin cash wallet api  This API is currently in *active* development, breaking changes may be made prior to official release of version 1.0.0. 
 *
 * API version: 4.0.0-next.12
 * Contact: hello@mainnet.cash
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TokenMintRequest struct for TokenMintRequest
type TokenMintRequest struct {
	// The walletId to make a request to.
	WalletId string `json:"walletId"`
	// One or more mint requests. Requests can span multiple categories; minting NFTs of each category are spent and recreated within the same transaction.
	Requests []TokenMintItem `json:"requests"`
	// If the minting NFT for a category contains a fungible amount, deduct from it by the number of mints requested for that category.
	DeductTokenAmount bool `json:"deductTokenAmount,omitempty"`
}
