/*
 * Mainnet Cash
 *
 * A developer friendly bitcoin cash wallet api  This API is currently in *active* development, breaking changes may be made prior to official release of version 1.0.0. 
 *
 * API version: 1.0.16
 * Contact: hello@mainnet.cash
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// SlpDepositAddressResponse struct for SlpDepositAddressResponse
type SlpDepositAddressResponse struct {
	Slpaddr string `json:"slpaddr,omitempty"`
}
