/*
 * Mainnet Cash
 *
 * A developer friendly bitcoin cash wallet api  This API is currently in *active* development, breaking changes may be made prior to official release of version 1.0.0. 
 *
 * API version: 2.7.21
 * Contact: hello@mainnet.cash
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InOutput struct for InOutput
type InOutput struct {
	// address in cashaddr format
	Address string `json:"address,omitempty"`
	// value in satoshis
	Value float32 `json:"value,omitempty"`
	Token *Token `json:"token,omitempty"`
}
