/*
 * Mainnet Cash
 *
 * A developer friendly bitcoin cash wallet api  This API is currently in *active* development, breaking changes may be made prior to official release of version 1.0.0. 
 *
 * API version: 1.1.14
 * Contact: hello@mainnet.cash
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// SmartBchDepositAddressResponse struct for SmartBchDepositAddressResponse
type SmartBchDepositAddressResponse struct {
	Address string `json:"address,omitempty"`
}
