/*
 * Mainnet Cash
 *
 * A developer friendly bitcoin cash wallet api  This API is currently in *active* development, breaking changes may be made prior to official release of version 1.0.0. 
 *
 * API version: 4.0.0-next.12
 * Contact: hello@mainnet.cash
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TokenGenesisRequest struct for TokenGenesisRequest
type TokenGenesisRequest struct {
	// The walletId to make a request to.
	WalletId string `json:"walletId"`
	// One or more genesis requests. Each consumes a distinct vout=0 input and creates a new token category in the same transaction.
	Requests []TokenGenesisItem `json:"requests"`
	// Single or an array of extra send requests (OP_RETURN, value transfer, etc.) to include in genesis transaction.
	SendRequests AnyOfSendRequestItemarrayTokenSendRequestOpReturnData `json:"sendRequests,omitempty"`
}
