/*
 * Mainnet Cash
 *
 * A developer friendly bitcoin cash wallet api  This API is currently in *active* development, breaking changes may be made prior to official release of version 1.0.0. 
 *
 * API version: 0.3.8
 * Contact: hello@mainnet.cash
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// SendRequestOptions struct for SendRequestOptions
type SendRequestOptions struct {
	UtxoIds []string `json:"utxoIds,omitempty"`
	// Cash address to watch 
	ChangeAddress string `json:"changeAddress,omitempty"`
}
